const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Plugins.Button,
		C3.Plugins.Arr,
		C3.Plugins.TextBox,
		C3.Behaviors.Persist,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Arr.Acts.Insert,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Browser.Acts.RequestInstall,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Text.Acts.SetSize
	];
};
self.C3_JsPropNameTable = [
	{Title: 0},
	{Спрайт: 0},
	{Start: 0},
	{Game: 0},
	{Insert: 0},
	{List: 0},
	{Спрайт2: 0},
	{Yes: 0},
	{Next: 0},
	{End: 0},
	{Done: 0},
	{Skip: 0},
	{Restart: 0},
	{Home: 0},
	{Score: 0},
	{Lose: 0},
	{Массив: 0},
	{ВводТекста: 0},
	{Plus: 0},
	{Спрайт3: 0},
	{Запечатлеть: 0},
	{WordsList: 0},
	{ToMenu: 0},
	{RandWord: 0},
	{Спрайт4: 0},
	{Delete: 0},
	{CounterLabel: 0},
	{Counter: 0},
	{Браузер: 0},
	{Download: 0},
	{FirstStartMain: 0},
	{Counter_Done: 0},
	{Counter_Next: 0},
	{Rand: 0},
	{GlobalCounter: 0},
	{i: 0},
	{y: 0},
	{FirstStart: 0}
];

self.InstanceType = {
	Title: class extends self.ITextInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Start: class extends self.IButtonInstance {},
	Game: class extends self.IButtonInstance {},
	Insert: class extends self.IButtonInstance {},
	List: class extends self.IButtonInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Yes: class extends self.IButtonInstance {},
	Next: class extends self.IButtonInstance {},
	End: class extends self.ITextInstance {},
	Done: class extends self.ITextInstance {},
	Skip: class extends self.ITextInstance {},
	Restart: class extends self.IButtonInstance {},
	Home: class extends self.IButtonInstance {},
	Score: class extends self.ITextInstance {},
	Lose: class extends self.ITextInstance {},
	Массив: class extends self.IArrayInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	Plus: class extends self.IButtonInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	WordsList: class extends self.ITextInstance {},
	ToMenu: class extends self.IButtonInstance {},
	RandWord: class extends self.ITextInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Delete: class extends self.ISpriteInstance {},
	CounterLabel: class extends self.ITextInstance {},
	Counter: class extends self.ITextInstance {},
	Браузер: class extends self.IInstance {},
	Download: class extends self.IButtonInstance {}
}